# Site settings
title: "ITinerary"
author:
  name: Claus Gerull
  twitter: cgerull
  github: cgerull
description: "A static blog where I keep my cheatsheets, recipes and information about procedures and more general tips. In short, my route through Information Technology."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://it.gerull.nl" # the base hostname & protocol for your site
lang: "en"
theme: jekyll-theme-cayman
# logo:
#   path: "/img/favicons/android-chrome-192x192.png"
#   width: 192
#   height: 192

# analytics:
#   google: UA-65400010-1

# adsense:
#   ad-client: ca-pub-8140733006923933

# comments:
# disqus: tips-tutorials

# build
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude:
  - CNAME
  - Gemfile
  - LICENSE
  - Rakefile
  - README.md
  - vendor/
  - vnu/
  - vnu.zip

sass:
  sass_dir: _sass
  style: compressed

compress_html:
  clippings: all
  endings: all
  comments: ["<!--", "-->"]
  ignore:
    envs: [travis]
